# Generated by Django 5.2 on 2025-04-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=300)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='posts/')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
