# Generated by Django 5.2 on 2025-04-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega3', '0003_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='bio',
        ),
        migrations.AddField(
            model_name='perfil',
            name='preferencias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
