# Generated by Django 5.2 on 2025-04-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega3', '0004_remove_perfil_bio_perfil_preferencias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
